# Generated by Django 3.2.9 on 2023-01-04 21:10

import apps.api.utils
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_set_up_services_certifications"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "s3_url",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.api.utils.document_upload_path,
                    ),
                ),
                ("file_size", models.IntegerField(blank=True, null=True)),
                ("upload_finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "mineral",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="api.mineral",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="api.property",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="servicecompany",
            name="look_for_properties",
            field=models.CharField(
                choices=[
                    ("Producing", "Producing"),
                    ("Non-Producing", "Non-Producing"),
                    ("Not Sure", "Not Sure"),
                ],
                max_length=20,
                verbose_name="Looking for properties that are",
            ),
        ),
        migrations.DeleteModel(
            name="MineralDocument",
        ),
    ]
