# Generated by Django 3.2.9 on 2023-01-04 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_auto_20230104_2110"),
    ]

    operations = [
        migrations.RenameField(
            model_name="document",
            old_name="property",
            new_name="proprty",
        ),
    ]
