# Generated by Django 3.2.9 on 2023-01-09 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_rename_property_document_proprty"),
    ]

    operations = [
        migrations.RenameField(
            model_name="document",
            old_name="proprty",
            new_name="property",
        ),
    ]
