# Generated by Django 3.2.9 on 2023-01-12 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_rename_proprty_document_property"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mineral",
            name="mineral_type",
        ),
    ]
