# Generated by Django 3.2.9 on 2023-01-17 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_set_up_mineral_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inquiryservicecompany",
            name="inquiry",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inquiry_service_companies",
                to="api.inquiry",
            ),
        ),
        migrations.AlterField(
            model_name="servicecompany",
            name="look_for_minerals",
            field=models.ManyToManyField(
                to="api.MineralType", verbose_name="Minerals you are looking for"
            ),
        ),
    ]
