# Generated by Django 3.2.9 on 2023-01-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_auto_20230117_1350"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
