# Generated by Django 3.2.9 on 2023-01-17 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_message_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="attachment",
        ),
        migrations.AddField(
            model_name="document",
            name="message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="api.message",
            ),
        ),
    ]
