# Generated by Django 3.2.9 on 2023-01-18 18:06

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_auto_20230117_1809"),
    ]

    operations = [
        migrations.CreateModel(
            name="CertificationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        choices=[
                            ("Registered Landman", "Registered Landman"),
                            (
                                "Registered Petroleum Landman",
                                "Registered Petroleum Landman",
                            ),
                            (
                                "Certified Petroleum Landman",
                                "Certified Petroleum Landman",
                            ),
                            (
                                "Certified Professional Lease and Title Analyst",
                                "Certified Professional Lease and Title Analyst",
                            ),
                            ("Petroleum Land Management", "Petroleum Land Management"),
                            (
                                "Certified Public Accountant",
                                "Certified Public Accountant",
                            ),
                            (
                                "Certified Financial Planner",
                                "Certified Financial Planner",
                            ),
                            ("Juris Doctor", "Juris Doctor"),
                            ("Oil, Gas, and Mineral Law", "Oil, Gas, and Mineral Law"),
                            (
                                "Estate Planning and Probate Law",
                                "Estate Planning and Probate Law",
                            ),
                            (
                                "Registered Mineral Manager",
                                "Registered Mineral Manager",
                            ),
                            (
                                "Certified Minerals Manager",
                                "Certified Minerals Manager",
                            ),
                            (
                                "Certified Trust and Fiduciary Advisor",
                                "Certified Trust and Fiduciary Advisor",
                            ),
                            (
                                "Certificate in Trust Administration",
                                "Certificate in Trust Administration",
                            ),
                            ("Accredited Estate Planner", "Accredited Estate Planner"),
                            (
                                "Chartered Trust and Estate Planners",
                                "Chartered Trust and Estate Planners",
                            ),
                            ("Certified Estate Planner", "Certified Estate Planner"),
                            (
                                "Certified Division Order Analyst",
                                "Certified Division Order Analyst",
                            ),
                        ],
                        max_length=128,
                        verbose_name="Certification Type Title",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="servicecompany",
            name="certifications",
        ),
        migrations.RemoveField(
            model_name="servicecompanycertification",
            name="certification",
        ),
    ]
