# Generated by Django 3.2.9 on 2023-01-18 18:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_auto_20230118_1806"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceCompanyCertificationRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "certification_number",
                    models.CharField(
                        max_length=128, verbose_name="Certification Number"
                    ),
                ),
                (
                    "certification_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.certificationtype",
                    ),
                ),
                (
                    "service_company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.servicecompany",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="ServiceCompanyCertification",
        ),
    ]
