# Generated by Django 3.2.9 on 2023-01-18 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_set_up_certification_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicecompany",
            name="certification_types",
            field=models.ManyToManyField(
                through="api.ServiceCompanyCertificationRelation",
                to="api.CertificationType",
            ),
        ),
        migrations.AlterField(
            model_name="servicecompanycertificationrelation",
            name="service_company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="certifications",
                to="api.servicecompany",
            ),
        ),
    ]
