# Generated by Django 3.2.16 on 2023-01-23 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('api', '0015_auto_20230118_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='category',
            field=models.CharField(choices=[('Buy / Grow Portfolio', 'Buy / Grow Portfolio'), ('Sell', 'Sell'), ('Get Connected with Service', 'Get Connected with Service'), ('Visitor', 'Visitor')], max_length=64, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inquiries', to='api.landowner'),
        ),
        migrations.AlterField(
            model_name='inquiryservicecompany',
            name='service_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inquiries', to='api.servicecompany'),
        ),
        migrations.AlterField(
            model_name='landowner',
            name='attorney_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attorney_owners', to='cities_light.city'),
        ),
        migrations.AlterField(
            model_name='landowner',
            name='attorney_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attorney_owners', to='cities_light.region'),
        ),
    ]
