# Generated by Django 3.2.16 on 2023-01-23 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20230123_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecompany',
            name='photo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.document'),
        ),
    ]
