# Generated by Django 3.2.16 on 2023-01-23 19:10

import apps.api.utils
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_servicecompany_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID')),
                ('s3_url', models.FileField(blank=True, null=True, upload_to=apps.api.utils.document_upload_path)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('upload_finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='servicecompany',
            name='photo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.picture'),
        ),
    ]
